import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import QueryProvider from "./provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="flex sm:justify-center space-x-4">
          {[
            ["Home", "/"],
            ["   about", "/about"],
            [" report", "/report"],
            ["todos-csr", "/rendering/csr"],
            ["todos-ssr", "/rendering/ssr"],
          ].map(([title, url]) => (
            <Link
              href={url}
              className="rounded-lg px-3 py-2 text-slate-700 font-medium hover:bg-slate-100 hover:text-slate-900"
            >
              {title}
            </Link>
          ))}
        </nav>
        <div>
          <QueryProvider>{children}</QueryProvider>
        </div>
      </body>
    </html>
  );
}
