import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import QueryProvider from "./provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Link href="/" className="grid justify-items-stretch">
          home
        </Link>
        <Link href="/about" className="grid justify-items-stretch">
          about
        </Link>
        <Link href="/report" className="grid justify-items-stretch">
          report
        </Link>
        <Link href="/rendering/csr" className="grid justify-items-stretch">
          todos-csr
        </Link>
        <Link href="/rendering/ssr" className="grid justify-items-stretch">
          todos-ssr
        </Link>
        <div>
          <QueryProvider>{children}</QueryProvider>
        </div>
      </body>
    </html>
  );
}
